-- Client and Project Management System for CogniVectra
-- Complete CRM and project tracking solution

-- =============================================
-- 1. CLIENTS TABLE
-- =============================================
CREATE TABLE IF NOT EXISTS public.clients (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  
  -- Client ID (auto-generated)
  client_id text UNIQUE, -- e.g., CL001, CL002
  
  -- Company Information
  company_name text NOT NULL,
  industry text,
  company_size text CHECK (company_size IN ('startup', '1-10', '11-50', '51-200', '201-500', '500+')),
  website text,
  
  -- Primary Contact
  primary_contact_name text NOT NULL,
  primary_contact_email text NOT NULL,
  primary_contact_phone text,
  primary_contact_title text,
  
  -- Additional Contacts (JSON array)
  additional_contacts jsonb DEFAULT '[]'::jsonb,
  
  -- Address
  address_line1 text,
  address_line2 text,
  city text,
  state text,
  country text DEFAULT 'India',
  pincode text,
  
  -- Business Details
  client_type text DEFAULT 'prospect' CHECK (client_type IN ('prospect', 'lead', 'active', 'inactive', 'churned')),
  lead_source text, -- e.g., 'website', 'referral', 'linkedin', 'cold outreach'
  
  -- Engagement
  services_interested text[], -- Array of services
  budget_range text,
  timeline text,
  
  -- Contract & Billing
  contract_type text CHECK (contract_type IN ('hourly', 'fixed', 'retainer', 'equity')),
  billing_cycle text CHECK (billing_cycle IN ('weekly', 'bi-weekly', 'monthly', 'milestone', 'one-time')),
  payment_terms text, -- e.g., 'Net 30', 'Net 15', '50% upfront'
  
  -- Financial
  total_revenue numeric(12, 2) DEFAULT 0,
  outstanding_balance numeric(12, 2) DEFAULT 0,
  
  -- Relationship
  account_manager_id bigint REFERENCES public.employees(id),
  relationship_status text DEFAULT 'new' CHECK (relationship_status IN ('new', 'nurturing', 'engaged', 'at_risk', 'healthy', 'champion')),
  
  -- Dates
  first_contact_date date,
  onboarding_completed_date date,
  last_interaction_date date,
  
  -- Documents
  contract_url text,
  nda_url text,
  
  -- Tags and Notes
  tags text[],
  notes text,
  
  -- Status
  is_active boolean DEFAULT true
);

-- =============================================
-- 2. PROJECTS TABLE
-- =============================================
CREATE TABLE IF NOT EXISTS public.projects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  
  -- Project ID (auto-generated)
  project_id text UNIQUE, -- e.g., PRJ001, PRJ002
  
  -- Basic Information
  project_name text NOT NULL,
  client_id bigint REFERENCES public.clients(id) NOT NULL,
  
  -- Project Details
  project_type text NOT NULL, -- e.g., 'Cloud Infrastructure', 'DevOps', 'SaaS Development'
  description text,
  objectives text,
  
  -- Scope
  deliverables text[],
  tech_stack text[],
  
  -- Timeline
  start_date date,
  estimated_end_date date,
  actual_end_date date,
  
  -- Status
  project_status text DEFAULT 'planning' CHECK (project_status IN (
    'planning', 'in_progress', 'on_hold', 'completed', 'cancelled', 'maintenance'
  )),
  health_status text DEFAULT 'on_track' CHECK (health_status IN (
    'on_track', 'at_risk', 'delayed', 'blocked'
  )),
  completion_percentage integer DEFAULT 0 CHECK (completion_percentage >= 0 AND completion_percentage <= 100),
  
  -- Team
  project_manager_id bigint REFERENCES public.employees(id),
  team_members jsonb DEFAULT '[]'::jsonb, -- Array of employee IDs with roles
  
  -- Financial
  project_value numeric(12, 2),
  budget numeric(12, 2),
  actual_cost numeric(12, 2) DEFAULT 0,
  billing_type text CHECK (billing_type IN ('hourly', 'fixed', 'milestone', 'retainer')),
  hourly_rate numeric(10, 2),
  
  -- Milestones (JSON array)
  milestones jsonb DEFAULT '[]'::jsonb,
  
  -- Communication
  slack_channel text,
  github_repo text,
  project_drive_url text,
  
  -- Risks and Issues
  risks text[],
  blockers text[],
  
  -- Documents
  proposal_url text,
  contract_url text,
  documentation_url text,
  
  -- Tags and Notes
  tags text[],
  notes text,
  
  -- Metadata
  priority text DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'critical')),
  is_billable boolean DEFAULT true,
  is_active boolean DEFAULT true
);

-- =============================================
-- 3. PROJECT TASKS TABLE
-- =============================================
CREATE TABLE IF NOT EXISTS public.project_tasks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  
  -- Task Details
  project_id bigint REFERENCES public.projects(id) NOT NULL,
  task_name text NOT NULL,
  description text,
  
  -- Assignment
  assigned_to bigint REFERENCES public.employees(id),
  
  -- Status
  task_status text DEFAULT 'todo' CHECK (task_status IN (
    'todo', 'in_progress', 'review', 'blocked', 'completed', 'cancelled'
  )),
  priority text DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'critical')),
  
  -- Timeline
  due_date date,
  completed_at timestamp with time zone,
  
  -- Effort
  estimated_hours numeric(6, 2),
  actual_hours numeric(6, 2),
  
  -- Dependencies
  depends_on bigint[], -- Array of task IDs
  
  -- Tags
  tags text[]
);

-- =============================================
-- 4. CLIENT INTERACTIONS TABLE
-- =============================================
CREATE TABLE IF NOT EXISTS public.client_interactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  
  -- Reference
  client_id bigint REFERENCES public.clients(id) NOT NULL,
  project_id bigint REFERENCES public.projects(id), -- Optional
  
  -- Interaction Details
  interaction_type text NOT NULL CHECK (interaction_type IN (
    'call', 'email', 'meeting', 'demo', 'proposal', 'contract', 'support', 'other'
  )),
  interaction_date timestamp with time zone DEFAULT timezone('utc'::text, now()),
  
  -- Content
  subject text,
  summary text NOT NULL,
  outcome text,
  
  -- Participants
  cognivectra_participants text[], -- Employee names
  client_participants text[], -- Client contact names
  
  -- Follow-up
  follow_up_required boolean DEFAULT false,
  follow_up_date date,
  follow_up_notes text,
  
  -- Recorded by
  recorded_by bigint REFERENCES public.employees(id)
);

-- =============================================
-- 5. INVOICES TABLE
-- =============================================
CREATE TABLE IF NOT EXISTS public.invoices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  
  -- Invoice ID (auto-generated)
  invoice_number text UNIQUE, -- e.g., INV-2026-001
  
  -- References
  client_id bigint REFERENCES public.clients(id) NOT NULL,
  project_id bigint REFERENCES public.projects(id),
  
  -- Invoice Details
  invoice_date date NOT NULL,
  due_date date NOT NULL,
  
  -- Line Items (JSON array)
  line_items jsonb NOT NULL, -- [{description, quantity, rate, amount}, ...]
  
  -- Amounts
  subtotal numeric(12, 2) NOT NULL,
  tax_percentage numeric(5, 2) DEFAULT 0,
  tax_amount numeric(12, 2) DEFAULT 0,
  total_amount numeric(12, 2) NOT NULL,
  
  -- Payment
  payment_status text DEFAULT 'draft' CHECK (payment_status IN (
    'draft', 'sent', 'viewed', 'partial', 'paid', 'overdue', 'cancelled'
  )),
  payment_date date,
  payment_method text,
  payment_reference text,
  
  -- Documents
  invoice_pdf_url text,
  
  -- Notes
  notes text,
  internal_notes text
);

-- =============================================
-- 6. ENABLE ROW LEVEL SECURITY
-- =============================================
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_interactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;

-- =============================================
-- 7. CREATE POLICIES (Admin only)
-- =============================================

-- Clients
DROP POLICY IF EXISTS "Admins can view clients" ON public.clients;
CREATE POLICY "Admins can view clients"
  ON public.clients FOR SELECT
  USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Admins can manage clients" ON public.clients;
CREATE POLICY "Admins can manage clients"
  ON public.clients FOR ALL
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- Projects
DROP POLICY IF EXISTS "Admins can view projects" ON public.projects;
CREATE POLICY "Admins can view projects"
  ON public.projects FOR SELECT
  USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Admins can manage projects" ON public.projects;
CREATE POLICY "Admins can manage projects"
  ON public.projects FOR ALL
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- Tasks
DROP POLICY IF EXISTS "Admins can view tasks" ON public.project_tasks;
CREATE POLICY "Admins can view tasks"
  ON public.project_tasks FOR SELECT
  USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Admins can manage tasks" ON public.project_tasks;
CREATE POLICY "Admins can manage tasks"
  ON public.project_tasks FOR ALL
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- Interactions
DROP POLICY IF EXISTS "Admins can view interactions" ON public.client_interactions;
CREATE POLICY "Admins can view interactions"
  ON public.client_interactions FOR SELECT
  USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Admins can manage interactions" ON public.client_interactions;
CREATE POLICY "Admins can manage interactions"
  ON public.client_interactions FOR ALL
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- Invoices
DROP POLICY IF EXISTS "Admins can view invoices" ON public.invoices;
CREATE POLICY "Admins can view invoices"
  ON public.invoices FOR SELECT
  USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Admins can manage invoices" ON public.invoices;
CREATE POLICY "Admins can manage invoices"
  ON public.invoices FOR ALL
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- =============================================
-- 8. CREATE INDEXES
-- =============================================

-- Clients
CREATE INDEX IF NOT EXISTS idx_clients_client_id ON public.clients(client_id);
CREATE INDEX IF NOT EXISTS idx_clients_company_name ON public.clients(company_name);
CREATE INDEX IF NOT EXISTS idx_clients_type ON public.clients(client_type);
CREATE INDEX IF NOT EXISTS idx_clients_active ON public.clients(is_active);
CREATE INDEX IF NOT EXISTS idx_clients_email ON public.clients(primary_contact_email);

-- Projects
CREATE INDEX IF NOT EXISTS idx_projects_project_id ON public.projects(project_id);
CREATE INDEX IF NOT EXISTS idx_projects_client_id ON public.projects(client_id);
CREATE INDEX IF NOT EXISTS idx_projects_status ON public.projects(project_status);
CREATE INDEX IF NOT EXISTS idx_projects_health ON public.projects(health_status);
CREATE INDEX IF NOT EXISTS idx_projects_active ON public.projects(is_active);

-- Tasks
CREATE INDEX IF NOT EXISTS idx_tasks_project_id ON public.project_tasks(project_id);
CREATE INDEX IF NOT EXISTS idx_tasks_assigned_to ON public.project_tasks(assigned_to);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON public.project_tasks(task_status);
CREATE INDEX IF NOT EXISTS idx_tasks_due_date ON public.project_tasks(due_date);

-- Interactions
CREATE INDEX IF NOT EXISTS idx_interactions_client_id ON public.client_interactions(client_id);
CREATE INDEX IF NOT EXISTS idx_interactions_project_id ON public.client_interactions(project_id);
CREATE INDEX IF NOT EXISTS idx_interactions_date ON public.client_interactions(interaction_date DESC);

-- Invoices
CREATE INDEX IF NOT EXISTS idx_invoices_number ON public.invoices(invoice_number);
CREATE INDEX IF NOT EXISTS idx_invoices_client_id ON public.invoices(client_id);
CREATE INDEX IF NOT EXISTS idx_invoices_project_id ON public.invoices(project_id);
CREATE INDEX IF NOT EXISTS idx_invoices_status ON public.invoices(payment_status);
CREATE INDEX IF NOT EXISTS idx_invoices_due_date ON public.invoices(due_date);

-- =============================================
-- 9. AUTO-GENERATE CLIENT ID
-- =============================================
CREATE OR REPLACE FUNCTION generate_client_id()
RETURNS TRIGGER AS $$
DECLARE
  next_id INTEGER;
  new_client_id TEXT;
BEGIN
  SELECT COALESCE(MAX(CAST(SUBSTRING(client_id FROM 3) AS INTEGER)), 0) + 1
  INTO next_id
  FROM public.clients
  WHERE client_id LIKE 'CL%';
  
  new_client_id := 'CL' || LPAD(next_id::TEXT, 3, '0');
  NEW.client_id := new_client_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_client_id ON public.clients;
CREATE TRIGGER set_client_id
  BEFORE INSERT ON public.clients
  FOR EACH ROW
  WHEN (NEW.client_id IS NULL)
  EXECUTE FUNCTION generate_client_id();

-- =============================================
-- 10. AUTO-GENERATE PROJECT ID
-- =============================================
CREATE OR REPLACE FUNCTION generate_project_id()
RETURNS TRIGGER AS $$
DECLARE
  next_id INTEGER;
  new_project_id TEXT;
BEGIN
  SELECT COALESCE(MAX(CAST(SUBSTRING(project_id FROM 4) AS INTEGER)), 0) + 1
  INTO next_id
  FROM public.projects
  WHERE project_id LIKE 'PRJ%';
  
  new_project_id := 'PRJ' || LPAD(next_id::TEXT, 3, '0');
  NEW.project_id := new_project_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_project_id ON public.projects;
CREATE TRIGGER set_project_id
  BEFORE INSERT ON public.projects
  FOR EACH ROW
  WHEN (NEW.project_id IS NULL)
  EXECUTE FUNCTION generate_project_id();

-- =============================================
-- 11. AUTO-GENERATE INVOICE NUMBER
-- =============================================
CREATE OR REPLACE FUNCTION generate_invoice_number()
RETURNS TRIGGER AS $$
DECLARE
  next_id INTEGER;
  year TEXT;
  new_invoice_number TEXT;
BEGIN
  year := TO_CHAR(CURRENT_DATE, 'YYYY');
  
  SELECT COALESCE(MAX(CAST(SUBSTRING(invoice_number FROM LENGTH(invoice_number) - 2) AS INTEGER)), 0) + 1
  INTO next_id
  FROM public.invoices
  WHERE invoice_number LIKE 'INV-' || year || '-%';
  
  new_invoice_number := 'INV-' || year || '-' || LPAD(next_id::TEXT, 3, '0');
  NEW.invoice_number := new_invoice_number;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_invoice_number ON public.invoices;
CREATE TRIGGER set_invoice_number
  BEFORE INSERT ON public.invoices
  FOR EACH ROW
  WHEN (NEW.invoice_number IS NULL)
  EXECUTE FUNCTION generate_invoice_number();

-- =============================================
-- 12. CREATE VIEWS FOR DASHBOARDS
-- =============================================

-- Client Summary View
DROP VIEW IF EXISTS public.client_summary;
CREATE OR REPLACE VIEW public.client_summary AS
SELECT 
  c.id,
  c.client_id,
  c.company_name,
  c.industry,
  c.client_type,
  c.relationship_status,
  c.primary_contact_name,
  c.primary_contact_email,
  c.total_revenue,
  c.outstanding_balance,
  c.is_active,
  COUNT(DISTINCT p.id) as active_projects,
  COUNT(DISTINCT i.id) as total_invoices,
  SUM(CASE WHEN i.payment_status = 'paid' THEN i.total_amount ELSE 0 END) as paid_amount,
  SUM(CASE WHEN i.payment_status IN ('sent', 'viewed', 'overdue') THEN i.total_amount ELSE 0 END) as pending_amount,
  e.full_name as account_manager_name
FROM public.clients c
LEFT JOIN public.projects p ON c.id = p.client_id AND p.is_active = true
LEFT JOIN public.invoices i ON c.id = i.client_id
LEFT JOIN public.employees e ON c.account_manager_id = e.id
GROUP BY c.id, e.full_name
ORDER BY c.created_at DESC;

-- Project Summary View
DROP VIEW IF EXISTS public.project_summary;
CREATE OR REPLACE VIEW public.project_summary AS
SELECT 
  p.id,
  p.project_id,
  p.project_name,
  p.client_id, -- Keep BIGINT client_id for foreign key operations
  p.project_type,
  p.project_status,
  p.health_status,
  p.completion_percentage,
  p.start_date,
  p.estimated_end_date,
  p.project_value,
  p.budget,
  p.actual_cost,
  c.company_name as client_name,
  c.client_id as client_code, -- Rename text client_id to client_code
  pm.full_name as project_manager_name,
  COUNT(DISTINCT pt.id) as total_tasks,
  COUNT(DISTINCT CASE WHEN pt.task_status = 'completed' THEN pt.id END) as completed_tasks,
  p.is_active
FROM public.projects p
LEFT JOIN public.clients c ON p.client_id = c.id
LEFT JOIN public.employees pm ON p.project_manager_id = pm.id
LEFT JOIN public.project_tasks pt ON p.id = pt.project_id
GROUP BY p.id, c.company_name, c.client_id, pm.full_name
ORDER BY p.created_at DESC;

-- Business Metrics View
DROP VIEW IF EXISTS public.business_metrics;
CREATE OR REPLACE VIEW public.business_metrics AS
SELECT 
  (SELECT COUNT(*) FROM public.clients WHERE is_active = true) as total_active_clients,
  (SELECT COUNT(*) FROM public.clients WHERE client_type = 'prospect') as total_prospects,
  (SELECT COUNT(*) FROM public.projects WHERE is_active = true) as total_active_projects,
  (SELECT COUNT(*) FROM public.projects WHERE project_status = 'in_progress') as projects_in_progress,
  (SELECT COUNT(*) FROM public.employees WHERE employment_status IN ('active', 'confirmed')) as total_active_employees,
  (SELECT SUM(total_revenue) FROM public.clients) as total_revenue,
  (SELECT SUM(outstanding_balance) FROM public.clients) as total_outstanding,
  (SELECT COUNT(*) FROM public.invoices WHERE payment_status = 'overdue') as overdue_invoices,
  (SELECT SUM(total_amount) FROM public.invoices WHERE payment_status IN ('sent', 'viewed', 'overdue')) as pending_payments;
