-- Careers Page Database Setup

-- 1. Create the 'job_postings' table
create table public.job_postings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Job Details
  title text not null,
  slug text not null unique,
  department text not null,
  location text not null,
  job_type text not null check (job_type in ('full-time', 'part-time', 'contract', 'internship')),
  experience_level text not null check (experience_level in ('entry', 'mid', 'senior', 'lead', 'executive')),
  
  -- Job Description
  summary text not null,
  description text not null,
  responsibilities text[], -- Array of responsibilities
  requirements text[], -- Array of requirements
  nice_to_have text[], -- Array of nice-to-have skills
  
  -- Compensation & Benefits
  salary_range text,
  benefits text[],
  
  -- Status
  status text default 'active' check (status in ('draft', 'active', 'paused', 'closed')),
  applications_count integer default 0,
  
  -- SEO
  meta_description text,
  
  -- Posting dates
  posted_at timestamp with time zone default timezone('utc'::text, now()),
  closing_at timestamp with time zone
);

-- 2. Create the 'job_applications' table
create table public.job_applications (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Applicant Information
  full_name text not null,
  email text not null,
  phone text,
  linkedin_url text,
  portfolio_url text,
  
  -- Application Details
  position text not null,
  job_posting_id bigint references public.job_postings(id) on delete set null,
  experience_years integer,
  current_location text,
  expected_salary text,
  notice_period text,
  cover_letter text,
  
  -- Resume Storage
  resume_url text not null,
  resume_filename text not null,
  
  -- Status Tracking
  status text default 'new' check (status in ('new', 'reviewing', 'shortlisted', 'interviewed', 'rejected', 'hired')),
  notes text,
  reviewed_at timestamp with time zone,
  reviewed_by text
);

-- 3. Enable Row Level Security (RLS)
alter table public.job_postings enable row level security;
alter table public.job_applications enable row level security;

-- 4. Create Policies for Job Postings

-- Allow everyone to view active job postings
create policy "Anyone can view active job postings"
  on public.job_postings for select
  using (status = 'active');

-- Only authenticated admins can manage job postings
create policy "Admins can manage job postings"
  on public.job_postings for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

-- 5. Create Policies for Job Applications

-- Allow anyone to submit applications (insert only)
create policy "Anyone can submit job applications"
  on public.job_applications for insert
  with check (true);

-- Only authenticated admins can view applications
create policy "Admins can view all applications"
  on public.job_applications for select
  using (auth.role() = 'authenticated');

-- Only authenticated admins can update applications
create policy "Admins can update applications"
  on public.job_applications for update
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

-- 4. Create a storage bucket for resumes
insert into storage.buckets (id, name, public) 
values ('resumes', 'resumes', false)
on conflict (id) do nothing;

-- 5. Storage Policies

-- Allow anyone to upload resumes (they'll only have access during upload)
create policy "Anyone can upload resumes"
  on storage.objects for insert
  with check (bucket_id = 'resumes');

-- Only authenticated admins can view resumes
create policy "Admins can view resumes"
  on storage.objects for select
  using (bucket_id = 'resumes' and auth.role() = 'authenticated');

-- Only authenticated admins can delete resumes
create policy "Admins can delete resumes"
  on storage.objects for delete
  using (bucket_id = 'resumes' and auth.role() = 'authenticated');

-- 6. Create indexes for faster queries

-- Job Applications indexes
create index idx_job_applications_status on public.job_applications(status);
create index idx_job_applications_created_at on public.job_applications(created_at desc);
create index idx_job_applications_email on public.job_applications(email);
create index idx_job_applications_job_posting_id on public.job_applications(job_posting_id);

-- Job Postings indexes
create index idx_job_postings_status on public.job_postings(status);
create index idx_job_postings_slug on public.job_postings(slug);
create index idx_job_postings_department on public.job_postings(department);
create index idx_job_postings_posted_at on public.job_postings(posted_at desc);
