-- Compensation Management System for CogniVectra
-- This schema manages salary packages and benefits for different roles

-- 1. Create compensation_packages table
CREATE TABLE public.compensation_packages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  
  -- Role Information
  role_title text NOT NULL,
  role_level text NOT NULL CHECK (role_level IN ('entry', 'mid', 'senior', 'lead', 'executive')),
  department text NOT NULL,
  
  -- Compensation Details (in INR, can be converted)
  currency text DEFAULT 'INR' CHECK (currency IN ('INR', 'USD', 'EUR')),
  annual_ctc_min numeric(12, 2) NOT NULL,
  annual_ctc_max numeric(12, 2) NOT NULL,
  
  -- Salary Breakdown
  basic_salary_percentage numeric(5, 2) DEFAULT 50.00, -- % of CTC
  hra_percentage numeric(5, 2) DEFAULT 20.00,
  special_allowance_percentage numeric(5, 2) DEFAULT 20.00,
  performance_bonus_percentage numeric(5, 2) DEFAULT 10.00,
  
  -- Benefits (stored as JSON array)
  benefits jsonb DEFAULT '[]'::jsonb,
  
  -- Leave Policy
  annual_leave_days integer DEFAULT 21,
  sick_leave_days integer DEFAULT 12,
  casual_leave_days integer DEFAULT 7,
  
  -- Working Conditions
  working_hours_per_week integer DEFAULT 40,
  work_schedule text DEFAULT 'Monday to Friday, 9 AM to 6 PM',
  work_location text DEFAULT 'Remote',
  
  -- Employment Terms
  probation_period_months integer DEFAULT 3,
  notice_period_days integer DEFAULT 60,
  
  -- Status
  is_active boolean DEFAULT true,
  
  -- Notes
  notes text
);

-- 2. Enable Row Level Security
ALTER TABLE public.compensation_packages ENABLE ROW LEVEL SECURITY;

-- 3. Create Policies

-- Only authenticated admins can view compensation packages
CREATE POLICY "Admins can view compensation packages"
  ON public.compensation_packages FOR SELECT
  USING (auth.role() = 'authenticated');

-- Only authenticated admins can manage compensation packages
CREATE POLICY "Admins can manage compensation packages"
  ON public.compensation_packages FOR ALL
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- 4. Create indexes for faster queries
CREATE INDEX idx_compensation_role_title ON public.compensation_packages(role_title);
CREATE INDEX idx_compensation_role_level ON public.compensation_packages(role_level);
CREATE INDEX idx_compensation_department ON public.compensation_packages(department);
CREATE INDEX idx_compensation_active ON public.compensation_packages(is_active);

-- 5. Insert sample compensation packages

INSERT INTO public.compensation_packages (
  role_title, role_level, department, currency,
  annual_ctc_min, annual_ctc_max,
  basic_salary_percentage, hra_percentage, special_allowance_percentage, performance_bonus_percentage,
  benefits,
  annual_leave_days, sick_leave_days, casual_leave_days,
  working_hours_per_week, work_schedule, work_location,
  probation_period_months, notice_period_days,
  is_active, notes
) VALUES
-- Engineering Roles
(
  'Junior Software Engineer', 'entry', 'Engineering', 'INR',
  600000, 900000,
  50.00, 20.00, 20.00, 10.00,
  '["Health insurance for self", "Remote work flexibility", "Learning budget ₹25,000/year", "Latest laptop and accessories", "Flexible working hours"]'::jsonb,
  18, 12, 7,
  40, 'Monday to Friday, flexible hours', 'Remote',
  3, 30,
  true, 'Entry-level software engineering role'
),
(
  'Software Engineer', 'mid', 'Engineering', 'INR',
  1200000, 1800000,
  50.00, 20.00, 20.00, 10.00,
  '["Health insurance for self and family", "Remote work flexibility", "Learning budget ₹50,000/year", "Latest MacBook Pro and accessories", "Flexible working hours"]'::jsonb,
  21, 12, 7,
  40, 'Monday to Friday, flexible hours', 'Remote',
  3, 60,
  true, 'Mid-level software engineering role'
),
(
  'Senior Software Engineer', 'senior', 'Engineering', 'INR',
  2000000, 3000000,
  50.00, 20.00, 20.00, 10.00,
  '["Comprehensive health insurance for family", "100% remote work", "Learning budget ₹75,000/year", "Latest MacBook Pro and accessories", "Annual team offsites", "Stock options (if applicable)"]'::jsonb,
  24, 12, 7,
  40, 'Monday to Friday, flexible hours with core hours 11 AM - 4 PM IST', 'Remote',
  3, 60,
  true, 'Senior software engineering role with mentorship responsibilities'
),
(
  'DevOps Engineer', 'mid', 'Engineering', 'INR',
  1500000, 2200000,
  50.00, 20.00, 20.00, 10.00,
  '["Health insurance for self and family", "Remote work flexibility", "Cloud certification budget ₹50,000/year", "Latest MacBook Pro and accessories", "Flexible working hours"]'::jsonb,
  21, 12, 7,
  40, 'Monday to Friday, flexible hours', 'Remote',
  3, 60,
  true, 'DevOps engineering role'
),
(
  'Senior DevOps Engineer', 'senior', 'Engineering', 'INR',
  2500000, 3500000,
  50.00, 20.00, 20.00, 10.00,
  '["Comprehensive health insurance for family", "100% remote work", "Cloud certification budget ₹75,000/year", "Latest MacBook Pro and accessories", "Annual team offsites", "On-call allowance"]'::jsonb,
  24, 12, 7,
  40, 'Monday to Friday, flexible hours with on-call rotation', 'Remote',
  3, 60,
  true, 'Senior DevOps role with infrastructure ownership'
),

-- Product/Design Roles
(
  'Product Manager', 'mid', 'Product', 'INR',
  1800000, 2500000,
  50.00, 20.00, 20.00, 10.00,
  '["Health insurance for self and family", "Remote work flexibility", "Conference budget ₹50,000/year", "Latest MacBook Pro and accessories", "Flexible working hours"]'::jsonb,
  21, 12, 7,
  40, 'Monday to Friday, flexible hours', 'Remote',
  3, 60,
  true, 'Product management role'
),
(
  'UX/UI Designer', 'mid', 'Design', 'INR',
  1200000, 1800000,
  50.00, 20.00, 20.00, 10.00,
  '["Health insurance for self and family", "Remote work flexibility", "Design tools subscription", "Latest MacBook Pro and accessories", "Flexible working hours"]'::jsonb,
  21, 12, 7,
  40, 'Monday to Friday, flexible hours', 'Remote',
  3, 60,
  true, 'UX/UI design role'
),

-- Sales/Marketing Roles
(
  'Sales Executive', 'mid', 'Sales', 'INR',
  800000, 1200000,
  40.00, 20.00, 20.00, 20.00,
  '["Health insurance for self", "Travel allowance", "Commission on sales", "Mobile and internet reimbursement", "Flexible working hours"]'::jsonb,
  21, 12, 7,
  40, 'Monday to Friday, flexible hours', 'Hybrid',
  3, 30,
  true, 'Sales role with commission structure'
),
(
  'Marketing Manager', 'senior', 'Marketing', 'INR',
  1500000, 2200000,
  50.00, 20.00, 20.00, 10.00,
  '["Health insurance for self and family", "Remote work flexibility", "Marketing tools budget", "Conference attendance", "Flexible working hours"]'::jsonb,
  21, 12, 7,
  40, 'Monday to Friday, flexible hours', 'Remote',
  3, 60,
  true, 'Marketing management role'
);

-- 6. Create a view for easy salary calculation
CREATE OR REPLACE VIEW public.compensation_breakdown AS
SELECT 
  id,
  role_title,
  role_level,
  department,
  currency,
  annual_ctc_min,
  annual_ctc_max,
  -- Calculate mid-point CTC
  (annual_ctc_min + annual_ctc_max) / 2 AS annual_ctc_mid,
  -- Calculate components based on mid-point
  ROUND((annual_ctc_min + annual_ctc_max) / 2 * basic_salary_percentage / 100, 2) AS basic_salary,
  ROUND((annual_ctc_min + annual_ctc_max) / 2 * hra_percentage / 100, 2) AS hra,
  ROUND((annual_ctc_min + annual_ctc_max) / 2 * special_allowance_percentage / 100, 2) AS special_allowance,
  ROUND((annual_ctc_min + annual_ctc_max) / 2 * performance_bonus_percentage / 100, 2) AS performance_bonus,
  benefits,
  annual_leave_days,
  sick_leave_days,
  casual_leave_days,
  working_hours_per_week,
  work_schedule,
  work_location,
  probation_period_months,
  notice_period_days,
  is_active
FROM public.compensation_packages;
