-- Employee Management System for CogniVectra
-- Tracks hired employees, their details, and employment status

-- 1. Create employees table
CREATE TABLE public.employees (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  
  -- Personal Information
  full_name text NOT NULL,
  email text NOT NULL UNIQUE,
  phone text,
  date_of_birth date,
  
  -- Address
  address_line1 text,
  address_line2 text,
  city text,
  state text,
  pincode text,
  country text DEFAULT 'India',
  
  -- Employment Details
  employee_id text UNIQUE, -- e.g., COGNI001
  job_title text NOT NULL,
  department text NOT NULL,
  role_level text CHECK (role_level IN ('entry', 'mid', 'senior', 'lead', 'executive')),
  reporting_manager text,
  
  -- Dates
  joining_date date NOT NULL,
  probation_end_date date,
  confirmation_date date,
  resignation_date date,
  last_working_date date,
  
  -- Compensation (linked to compensation package)
  compensation_package_id bigint REFERENCES public.compensation_packages(id),
  annual_ctc numeric(12, 2) NOT NULL,
  currency text DEFAULT 'INR',
  
  -- Work Details
  work_location text DEFAULT 'Remote',
  work_schedule text,
  employment_type text DEFAULT 'full-time' CHECK (employment_type IN ('full-time', 'part-time', 'contract', 'intern')),
  
  -- Leave Balance
  annual_leave_balance integer DEFAULT 0,
  sick_leave_balance integer DEFAULT 0,
  casual_leave_balance integer DEFAULT 0,
  
  -- Documents
  offer_letter_url text,
  contract_url text,
  id_proof_url text,
  resume_url text,
  
  -- Status
  employment_status text DEFAULT 'active' CHECK (employment_status IN ('offer_sent', 'offer_accepted', 'active', 'on_probation', 'confirmed', 'notice_period', 'resigned', 'terminated')),
  
  -- Links to other tables
  job_application_id bigint REFERENCES public.job_applications(id),
  
  -- Emergency Contact
  emergency_contact_name text,
  emergency_contact_phone text,
  emergency_contact_relation text,
  
  -- Bank Details (for payroll)
  bank_name text,
  bank_account_number text,
  bank_ifsc_code text,
  pan_number text,
  
  -- Notes
  notes text
);

-- 2. Create offer_letters table (tracks generated offers)
CREATE TABLE public.offer_letters (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  
  -- Reference
  offer_reference text NOT NULL UNIQUE, -- e.g., COGNI/2026/001
  
  -- Candidate Information
  candidate_name text NOT NULL,
  candidate_email text NOT NULL,
  candidate_address jsonb, -- Store full address as JSON
  
  -- Job Details
  job_title text NOT NULL,
  department text NOT NULL,
  reporting_manager text,
  work_location text,
  job_responsibilities text,
  
  -- Employment Terms
  start_date date NOT NULL,
  employment_type text DEFAULT 'full-time permanent',
  probation_period text,
  
  -- Compensation (stored at time of offer)
  annual_ctc text NOT NULL,
  basic_salary text,
  hra text,
  special_allowance text,
  performance_bonus text,
  other_benefits text,
  
  -- Benefits
  benefits jsonb DEFAULT '[]'::jsonb,
  
  -- Working Conditions
  working_hours text,
  work_schedule text,
  annual_leave_days text,
  sick_leave_days text,
  casual_leave_days text,
  
  -- Terms
  notice_period_days text,
  additional_conditions text,
  
  -- Signatory
  signatory_name text,
  signatory_title text,
  
  -- Offer Status
  offer_status text DEFAULT 'draft' CHECK (offer_status IN ('draft', 'sent', 'accepted', 'rejected', 'expired')),
  sent_at timestamp with time zone,
  acceptance_deadline date,
  accepted_at timestamp with time zone,
  rejected_at timestamp with time zone,
  
  -- Generated Files
  offer_letter_html text, -- Full HTML of the offer
  offer_letter_pdf_url text, -- URL to PDF if generated
  
  -- Links
  job_application_id bigint REFERENCES public.job_applications(id),
  compensation_package_id bigint REFERENCES public.compensation_packages(id),
  employee_id bigint REFERENCES public.employees(id), -- Linked after acceptance
  
  -- Notes
  notes text
);

-- 3. Enable Row Level Security
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.offer_letters ENABLE ROW LEVEL SECURITY;

-- 4. Create Policies

-- Employees - Only admins can view and manage
CREATE POLICY "Admins can view employees"
  ON public.employees FOR SELECT
  USING (auth.role() = 'authenticated');

CREATE POLICY "Admins can manage employees"
  ON public.employees FOR ALL
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- Offer Letters - Only admins can view and manage
CREATE POLICY "Admins can view offer letters"
  ON public.offer_letters FOR SELECT
  USING (auth.role() = 'authenticated');

CREATE POLICY "Admins can manage offer letters"
  ON public.offer_letters FOR ALL
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- 5. Create indexes for faster queries

-- Employees indexes
CREATE INDEX idx_employees_email ON public.employees(email);
CREATE INDEX idx_employees_employee_id ON public.employees(employee_id);
CREATE INDEX idx_employees_status ON public.employees(employment_status);
CREATE INDEX idx_employees_department ON public.employees(department);
CREATE INDEX idx_employees_joining_date ON public.employees(joining_date DESC);

-- Offer Letters indexes
CREATE INDEX idx_offer_letters_reference ON public.offer_letters(offer_reference);
CREATE INDEX idx_offer_letters_email ON public.offer_letters(candidate_email);
CREATE INDEX idx_offer_letters_status ON public.offer_letters(offer_status);
CREATE INDEX idx_offer_letters_created ON public.offer_letters(created_at DESC);

-- 6. Create function to auto-generate employee ID
CREATE OR REPLACE FUNCTION generate_employee_id()
RETURNS TRIGGER AS $$
DECLARE
  next_id INTEGER;
  new_employee_id TEXT;
BEGIN
  -- Get the next employee number
  SELECT COALESCE(MAX(CAST(SUBSTRING(employee_id FROM 6) AS INTEGER)), 0) + 1
  INTO next_id
  FROM public.employees
  WHERE employee_id LIKE 'COGNI%';
  
  -- Generate new employee ID (e.g., COGNI001, COGNI002, etc.)
  new_employee_id := 'COGNI' || LPAD(next_id::TEXT, 3, '0');
  
  NEW.employee_id := new_employee_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 7. Create trigger to auto-generate employee ID
CREATE TRIGGER set_employee_id
  BEFORE INSERT ON public.employees
  FOR EACH ROW
  WHEN (NEW.employee_id IS NULL)
  EXECUTE FUNCTION generate_employee_id();

-- 8. Create function to auto-generate offer reference
CREATE OR REPLACE FUNCTION generate_offer_reference()
RETURNS TRIGGER AS $$
DECLARE
  next_id INTEGER;
  year TEXT;
  new_reference TEXT;
BEGIN
  -- Get current year
  year := TO_CHAR(CURRENT_DATE, 'YYYY');
  
  -- Get the next offer number for this year
  SELECT COALESCE(MAX(CAST(SUBSTRING(offer_reference FROM LENGTH(offer_reference) - 2) AS INTEGER)), 0) + 1
  INTO next_id
  FROM public.offer_letters
  WHERE offer_reference LIKE 'COGNI/' || year || '/%';
  
  -- Generate new reference (e.g., COGNI/2026/001)
  new_reference := 'COGNI/' || year || '/' || LPAD(next_id::TEXT, 3, '0');
  
  NEW.offer_reference := new_reference;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 9. Create trigger to auto-generate offer reference
CREATE TRIGGER set_offer_reference
  BEFORE INSERT ON public.offer_letters
  FOR EACH ROW
  WHEN (NEW.offer_reference IS NULL)
  EXECUTE FUNCTION generate_offer_reference();

-- 10. Create view for employee summary
CREATE OR REPLACE VIEW public.employee_summary AS
SELECT 
  e.id,
  e.employee_id,
  e.full_name,
  e.email,
  e.job_title,
  e.department,
  e.role_level,
  e.employment_status,
  e.joining_date,
  e.annual_ctc,
  e.currency,
  e.work_location,
  cp.role_title as compensation_role,
  CASE 
    WHEN e.employment_status = 'active' OR e.employment_status = 'confirmed' THEN 
      EXTRACT(YEAR FROM AGE(CURRENT_DATE, e.joining_date)) || ' years, ' ||
      EXTRACT(MONTH FROM AGE(CURRENT_DATE, e.joining_date)) || ' months'
    ELSE NULL
  END as tenure
FROM public.employees e
LEFT JOIN public.compensation_packages cp ON e.compensation_package_id = cp.id
ORDER BY e.joining_date DESC;

-- 11. Create view for offer letter summary
CREATE OR REPLACE VIEW public.offer_summary AS
SELECT 
  ol.id,
  ol.offer_reference,
  ol.candidate_name,
  ol.candidate_email,
  ol.job_title,
  ol.department,
  ol.annual_ctc,
  ol.start_date,
  ol.offer_status,
  ol.sent_at,
  ol.acceptance_deadline,
  ol.accepted_at,
  ol.created_at,
  ja.full_name as application_name,
  ja.position as applied_position
FROM public.offer_letters ol
LEFT JOIN public.job_applications ja ON ol.job_application_id = ja.id
ORDER BY ol.created_at DESC;
