-- 1. Create the 'posts' table
create table public.posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  slug text not null unique,
  title text not null,
  excerpt text,
  body text,
  image_url text,
  status text default 'draft' check (status in ('draft', 'pending_review', 'scheduled', 'published', 'archived')),
  published_at timestamp with time zone
);

-- 2. Enable Row Level Security (RLS)
alter table public.posts enable row level security;

-- 3. Create Policies

-- Allow everyone (public) to read 'published' posts
create policy "Public posts are viewable by everyone"
  on public.posts for select
  using ( status = 'published' );

-- Allow authenticated users (admin) to do everything
-- Note: You will need to sign in or use the service_role key for the scripts
create policy "Admins can do everything"
  on public.posts for all
  using ( auth.role() = 'authenticated' )
  with check ( auth.role() = 'authenticated' );

-- 4. Create a storage bucket for blog images (optional)
insert into storage.buckets (id, name, public) values ('blog-images', 'blog-images', true) on conflict (id) do nothing;

create policy "Images are publicly accessible"
  on storage.objects for select
  using ( bucket_id = 'blog-images' );

create policy "Admins can upload images"
  on storage.objects for insert
  with check ( bucket_id = 'blog-images' and auth.role() = 'authenticated' );

-- 5. AI Intelligence Tables

-- Feature Flags for routing and logging
CREATE TABLE IF NOT EXISTS public.ai_feature_flags (
    id          UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
    flag_name   TEXT        UNIQUE NOT NULL,
    is_enabled  BOOLEAN     DEFAULT FALSE,
    description TEXT,
    rollout_pct INTEGER     DEFAULT 0 CHECK (rollout_pct BETWEEN 0 AND 100),
    updated_at  TIMESTAMPTZ DEFAULT NOW(),
    updated_by  TEXT        DEFAULT 'system'
);

ALTER TABLE public.ai_feature_flags ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read flags" ON public.ai_feature_flags FOR SELECT USING (true);

-- Centralized Query Logging for AI Intent Routing
CREATE TABLE IF NOT EXISTS public.ai_query_logs (
    id            UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
    tenant_id     TEXT        NOT NULL,
    user_id       TEXT,
    query         TEXT        NOT NULL,
    intent        TEXT,
    confidence    FLOAT,
    agent_selected TEXT,
    response      TEXT,
    latency_ms    FLOAT,
    routing_path  TEXT DEFAULT 'keyword',
    error_detail  TEXT,
    created_at    TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.ai_query_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Service role can insert logs" ON public.ai_query_logs FOR INSERT WITH CHECK (true);
