-- 1. Create the 'posts' table
create table public.posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  slug text not null unique,
  title text not null,
  excerpt text,
  body text,
  image_url text,
  status text default 'draft' check (status in ('draft', 'pending_review', 'scheduled', 'published', 'archived')),
  published_at timestamp with time zone
);

-- 2. Enable Row Level Security (RLS)
alter table public.posts enable row level security;

-- 3. Create Policies

-- Allow everyone (public) to read 'published' posts
create policy "Public posts are viewable by everyone"
  on public.posts for select
  using ( status = 'published' );

-- Allow authenticated users (admin) to do everything
-- Note: You will need to sign in or use the service_role key for the scripts
create policy "Admins can do everything"
  on public.posts for all
  using ( auth.role() = 'authenticated' )
  with check ( auth.role() = 'authenticated' );

-- 4. Create a storage bucket for blog images (optional)
insert into storage.buckets (id, name, public) values ('blog-images', 'blog-images', true);

create policy "Images are publicly accessible"
  on storage.objects for select
  using ( bucket_id = 'blog-images' );

create policy "Admins can upload images"
  on storage.objects for insert
  with check ( bucket_id = 'blog-images' and auth.role() = 'authenticated' );
